version: '3'

dotenv: ['.env']
silent: true

tasks:
  build:
    cmds:
      - docker build -t niftnory-explorer:local .

  run:
    cmds:
      - docker run --name niftnory-explorer --env-file .env -p 8080:8080 -d niftnory-explorer:local

  id:
    cmds:
      - docker ps -aqf "name=^niftnory-explorer$"

  stop:
    cmds:
      - docker stop niftnory-explorer

  start:
    cmds:
      - docker start niftnory-explorer

  restart:
    cmds:
      - docker restart niftnory-explorer

  kill:
    cmds:
      - docker kill niftnory-explorer
